In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [8]:
from google. colab import drive
drive.mount ('/content/amjdrive')

Mounted at /content/amjdrive


In [13]:
df = pd.read_csv('/content/amjdrive/MyDrive/Phython/car driving risk analysis.csv')

In [14]:
df 

speed  risk
0     200    95
1      90    20
2     300    98
3     110    60
4     240    72
5     115    10
6      50     7
7     230    85
8     190    45
9     260    91
10    290    82
11    185    59
12    310    93
13     95    18
14     30     2

In [22]:
df.speed

0     200
1      90
2     300
3     110
4     240
5     115
6      50
7     230
8     190
9     260
10    290
11    185
12    310
13     95
14     30
Name: speed, dtype: int64

In [23]:
df.risk

0     95
1     20
2     98
3     60
4     72
5     10
6      7
7     85
8     45
9     91
10    82
11    59
12    93
13    18
14     2
Name: risk, dtype: int64

In [24]:
df.risk.median()

60.0

In [26]:
df.speed.median()

190.0

In [44]:
df.isnull().any()


speed    False
risk     False
dtype: bool

In [45]:
df.sum()

speed    2695
risk      837
dtype: int64

In [46]:
 
x=df[['speed']]
y=df['risk']

In [53]:
x

speed
0     200
1      90
2     300
3     110
4     240
5     115
6      50
7     230
8     190
9     260
10    290
11    185
12    310
13     95
14     30

In [54]:
y

0     95
1     20
2     98
3     60
4     72
5     10
6      7
7     85
8     45
9     91
10    82
11    59
12    93
13    18
14     2
Name: risk, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split

In [56]:

xtrain, xtest, ytrain, ytest=train_test_split(x,y,test_size=.40,random_state=1)

In [57]:
xtrain

speed
1      90
13     95
0     200
14     30
9     260
8     190
12    310
11    185
5     115

In [58]:
ytrain

1     20
13    18
0     95
14     2
9     91
8     45
12    93
11    59
5     10
Name: risk, dtype: int64

In [59]:
xtest

speed
3     110
7     230
6      50
2     300
10    290
4     240

In [60]:
ytest

3     60
7     85
6      7
2     98
10    82
4     72
Name: risk, dtype: int64

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
reg=LinearRegression()

In [63]:
reg.fit(xtrain, ytrain)


LinearRegression()

In [64]:
reg.predict(xtest)

array([ 27.15301215,  73.82259334,   3.81822156, 101.04651569,
        97.15738393,  77.7117251 ])

In [70]:
reg.predict([[260]])


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([85.48998863])

In [71]:

reg.coef_

array([0.38891318])

In [72]:
reg.intercept_

-15.62743726501705

In [73]:
0.38891318*260-15.62743726501705

85.48998953498295